version: "3.4"

services:
  whisper-asr-webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest
    environment:
      - ASR_ENGINE=whisperx
      - ASR_MODEL=base
      - HF_TOKEN=${HF_TOKEN:-}
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - cache-whisper:/root/.cache

volumes:
  cache-whisper:
